<a href="https://colab.research.google.com/github/otabekqoroboyev/data-science/blob/main/arifmetik_amallar_np.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy kutubxonasi bilan ishlash: 
Arifmetik amallar mavzusi 2023,02,12

In [1]:
import numpy as np

In [4]:
arr = np.arange(6).reshape(2,3) # 0dan 6 gacha tashkil topgan sonlar
arr1 = np.arange(6, 12).reshape(2,3) # 6 dan 11 gacha bo'lgan elementlardan tashkil topgan 
print(arr)
print(arr1)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [5]:
#ko'paytirish
arr*arr1 # arr va arr1 ni mos elementlarni ko'paytirib beradi

array([[ 0,  7, 16],
       [27, 40, 55]])

In [8]:
#bo'lish
arr1/arr

<ipython-input-8-90fcaa737967>:2: RuntimeWarning: divide by zero encountered in true_divide
  arr1/arr


array([[inf, 7. , 4. ],
       [3. , 2.5, 2.2]])

In [7]:
#qo'shish
arr+arr1

array([[ 6,  8, 10],
       [12, 14, 16]])

In [9]:
#ayrish
arr1-arr

array([[6, 6, 6],
       [6, 6, 6]])

In [10]:
#kvga oshrish
arr1**2

array([[ 36,  49,  64],
       [ 81, 100, 121]])

In [12]:
#kvadrat ildiz olish
arr1**0.5

array([[2.44948974, 2.64575131, 2.82842712],
       [3.        , 3.16227766, 3.31662479]])