<a href="https://colab.research.google.com/github/otabekqoroboyev/data-science/blob/main/array_oqlarini_almashtirish.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [4]:
A = np.arange(6).reshape(3,2) # ikkilik massiv reshape() metodi orqali beriladi arange()-sanq raqam berish uchun
A


array([[0, 1],
       [2, 3],
       [4, 5]])

In [6]:
A.T #massivni transpose o'tkazish uchun qo'llaniladi


array([[0, 2, 4],
       [1, 3, 5]])

In [7]:
A.swapaxes(1,0)

array([[0, 2, 4],
       [1, 3, 5]])

In [9]:
np.dot(A, A.T) # A va A^T hosil bolgan masiv

array([[ 1,  3,  5],
       [ 3, 13, 23],
       [ 5, 23, 41]])