<a href="https://colab.research.google.com/github/otabekqoroboyev/data-science/blob/main/boolean_np.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Boolean indekslash


In [1]:
import numpy as np

In [2]:
# Ismlar
names = np.array(['Hasan', 'Husan', 'Mirzabek', 'Elyor', 'Hasan', 'Javohir', 'Elyor'])
names

array(['Hasan', 'Husan', 'Mirzabek', 'Elyor', 'Hasan', 'Javohir', 'Elyor'],
      dtype='<U8')

In [6]:
data = np.random.randn(7,4)
data

array([[-2.66086613,  1.9559145 , -0.7013255 ,  0.6973912 ],
       [ 0.67259164,  0.327764  ,  0.49293457, -0.44049866],
       [-0.38946905,  0.44462094, -0.41374612,  0.7457713 ],
       [-1.38327486,  1.47773462,  0.81404265, -0.31196693],
       [ 1.79440309, -1.40756306, -0.23927566,  0.03573515],
       [-1.02331195,  1.15247084,  0.96262849, -0.71641499],
       [-2.29408599,  0.30231577,  2.37317678, -0.0214057 ]])

In [8]:
names == 'Hasan'

array([ True, False, False, False,  True, False, False])

In [9]:
data[names =='Hasan'] # hasanga tegishli barcha malumotlarni chaqirib oldi

array([[-2.66086613,  1.9559145 , -0.7013255 ,  0.6973912 ],
       [ 1.79440309, -1.40756306, -0.23927566,  0.03573515]])

In [11]:
data[names == "Husan"]

array([[ 0.67259164,  0.327764  ,  0.49293457, -0.44049866]])

In [13]:
data[names == 'Hasan', 2:]

array([[-0.7013255 ,  0.6973912 ],
       [-0.23927566,  0.03573515]])

In [15]:
data[names !='Hasan'] # (!=) hasandan tashqari barcha insonlarni ajratib olish

array([[ 0.67259164,  0.327764  ,  0.49293457, -0.44049866],
       [-0.38946905,  0.44462094, -0.41374612,  0.7457713 ],
       [-1.38327486,  1.47773462,  0.81404265, -0.31196693],
       [-1.02331195,  1.15247084,  0.96262849, -0.71641499],
       [-2.29408599,  0.30231577,  2.37317678, -0.0214057 ]])

In [17]:
data[~(names == 'Husan')]

array([[-2.66086613,  1.9559145 , -0.7013255 ,  0.6973912 ],
       [-0.38946905,  0.44462094, -0.41374612,  0.7457713 ],
       [-1.38327486,  1.47773462,  0.81404265, -0.31196693],
       [ 1.79440309, -1.40756306, -0.23927566,  0.03573515],
       [-1.02331195,  1.15247084,  0.96262849, -0.71641499],
       [-2.29408599,  0.30231577,  2.37317678, -0.0214057 ]])

In [23]:
data[names == "Hasan"],[names == "Husan"]

(array([[-2.66086613,  1.9559145 , -0.7013255 ,  0.6973912 ],
        [ 1.79440309, -1.40756306, -0.23927566,  0.03573515]]),
 [array([False,  True, False, False, False, False, False])])

In [24]:
print(names)
print(data)

['Hasan' 'Husan' 'Mirzabek' 'Elyor' 'Hasan' 'Javohir' 'Elyor']
[[-2.66086613  1.9559145  -0.7013255   0.6973912 ]
 [ 0.67259164  0.327764    0.49293457 -0.44049866]
 [-0.38946905  0.44462094 -0.41374612  0.7457713 ]
 [-1.38327486  1.47773462  0.81404265 -0.31196693]
 [ 1.79440309 -1.40756306 -0.23927566  0.03573515]
 [-1.02331195  1.15247084  0.96262849 -0.71641499]
 [-2.29408599  0.30231577  2.37317678 -0.0214057 ]]


In [26]:
mask =(names =='Hasan') | (names =="Husan") # | bu chiziq or yoki anosini anglatadi
mask

array([ True,  True, False, False,  True, False, False])

In [28]:
data[mask]

array([[-2.66086613,  1.9559145 , -0.7013255 ,  0.6973912 ],
       [ 0.67259164,  0.327764  ,  0.49293457, -0.44049866],
       [ 1.79440309, -1.40756306, -0.23927566,  0.03573515]])

In [31]:
data[data<0] = 0
data

array([[0.        , 1.9559145 , 0.        , 0.6973912 ],
       [0.67259164, 0.327764  , 0.49293457, 0.        ],
       [0.        , 0.44462094, 0.        , 0.7457713 ],
       [0.        , 1.47773462, 0.81404265, 0.        ],
       [1.79440309, 0.        , 0.        , 0.03573515],
       [0.        , 1.15247084, 0.96262849, 0.        ],
       [0.        , 0.30231577, 2.37317678, 0.        ]])