<a href="https://colab.research.google.com/github/otabekqoroboyev/data-science/blob/main/chiziqli_algebra_np.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Chiziqli Algebra
Numpy kutubxonasi

In [1]:
import numpy as np

In [6]:
x = np.array([[1,2,3], [4,5,6]])
x

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
y = np.array([[5,5,5],[4,4,4]]) # matrisa yaratib oldik
y

array([[5, 5, 5],
       [4, 4, 4]])

In [9]:
x+y 

array([[ 6,  7,  8],
       [ 8,  9, 10]])

In [10]:
y-x

array([[ 4,  3,  2],
       [ 0, -1, -2]])

In [11]:
x*5

array([[ 5, 10, 15],
       [20, 25, 30]])

In [12]:
x = np.array([[1,2,3], [4,5,6]])
x

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
y = np.array([[1,2],[1,7], [4,2]])
y

array([[1, 2],
       [1, 7],
       [4, 2]])

In [14]:
x.dot(y) # x*y ni qiymati

array([[15, 22],
       [33, 55]])

In [15]:
np.dot(x,y) # boshqa usuli ko'paytirishni 

array([[15, 22],
       [33, 55]])

In [16]:
y.dot(x) # y*x ga ko'paytirganda

array([[ 9, 12, 15],
       [29, 37, 45],
       [12, 18, 24]])

In [17]:
np.dot(y,x)

array([[ 9, 12, 15],
       [29, 37, 45],
       [12, 18, 24]])

In [19]:
# Linear algebra
from numpy.linalg import inv

In [49]:
a = np.array([1,2,3,5,8])
b = np.array([0,3,4,2,1])
c = a+b
c = c*a
print(c[2])

21


In [ ]:
|