<a href="https://colab.research.google.com/github/otabekqoroboyev/data-science/blob/main/fayllar_bn_np.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
np.save('data', arr) # faylni saqlab olish

In [6]:
arr2 = np.load('data.npy') #faylni o`qish uchun|

In [7]:
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
arr1 =np.arange(20)

In [10]:
np.savez('arrays', a=arr2, b = arr1)

In [11]:
arrays = np.load('arrays.npz')

In [15]:
arrays['b']

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [16]:
np.savez_compressed("array_comp", a=arr1, b='arr2')