<a href="https://colab.research.google.com/github/otabekqoroboyev/data-science/blob/main/mantiqiy_shart_operatori_np.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [5]:
xarr =([1.1, 1.2, 1.3, 1.4, 1.5 ])
yarr =([2.1, 2.2, 2.3, 2.4, 2.5])

In [6]:
cond = [True, False, True, True, False]

In [9]:
result =np.where(cond,xarr,yarr) #Cond == True: bo'sa xarr chiqaradi False bo'lsa yarr chiqaradi
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

### Shart operatori sifatida `where` dan foydalanish


In [11]:
arr =np.random.randn(4,4)
arr

array([[ 0.20592183,  1.18685694, -1.15151994,  1.04316942],
       [ 0.26244345,  0.03599592, -0.56057514, -0.08312646],
       [-1.080834  , -0.33156211, -0.61490635,  0.43906454],
       [-0.49183074, -0.40624026,  0.16236234, -0.06616962]])

In [15]:
results = np.where(arr<0, -2, 2) # agar arr masivmiz 0dan kichik bo'lsa -2 chiqaradi aksincha bo'lsa 2 ni chiqaradi
results

array([[ 2,  2, -2,  2],
       [ 2,  2, -2, -2],
       [-2, -2, -2,  2],
       [-2, -2,  2, -2]])