<a href="https://colab.research.google.com/github/otabekqoroboyev/data-science/blob/main/matematik_amalar_np.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np


# Numpy kutubxonasi bilan ishlash:
matematik amallar

In [2]:
arr = np.random.randn(5,4)
arr

array([[-1.2430834 , -1.10720972,  1.16306916,  0.58655841],
       [-0.4523355 , -0.31403163,  0.06432558,  2.3432724 ],
       [-1.12960293, -0.53013626, -0.31442037, -0.20360127],
       [ 0.13339751, -0.2692021 , -1.82335645, -0.14036558],
       [ 0.68891469, -0.1733988 , -0.29239759,  0.31029217]])

In [3]:
arr.sum()# arr ni barcha elementlarni yeg'indisini chiqaradi

-2.7033117050113096

In [4]:
np.sum(arr)

-2.7033117050113096

In [6]:
arr.sum(axis=1) # eniga hisoblab berdi 4ta element yegindisi

array([-0.60066556,  1.64123085, -2.17776084, -2.09952662,  0.53341046])

In [7]:
arr.sum(axis=0) # ustun bo'yicha yeg'indi 

array([-2.00270964, -2.39397852, -1.20277966,  2.89615612])

**mean** - o'rta arifmetik qiymat funksiyasi

In [9]:
data = np.arange(6)
data

array([0, 1, 2, 3, 4, 5])

In [11]:
np.mean(data)

2.5

In [12]:
print(arr)

[[-1.2430834  -1.10720972  1.16306916  0.58655841]
 [-0.4523355  -0.31403163  0.06432558  2.3432724 ]
 [-1.12960293 -0.53013626 -0.31442037 -0.20360127]
 [ 0.13339751 -0.2692021  -1.82335645 -0.14036558]
 [ 0.68891469 -0.1733988  -0.29239759  0.31029217]]


In [13]:
np.mean(arr) # arr barcha elementni yegindisini ortacha qiymati

-0.1351655852505655

In [14]:
np.mean(arr, axis=1) # bu qator bo'yicha o'rtacha qiymatni qaytaradi

array([-0.15016639,  0.41030771, -0.54444021, -0.52488166,  0.13335262])

In [15]:
np.mean(arr, axis=0) # bu ustun bo'yicha 

array([-0.40054193, -0.4787957 , -0.24055593,  0.57923122])

### `cumsum` metodi

In [16]:
data

array([0, 1, 2, 3, 4, 5])

In [18]:
np.cumsum(data) #o'zigacha bo'lganiga qo'shib boradi

array([ 0,  1,  3,  6, 10, 15])