<a href="https://colab.research.google.com/github/otabekqoroboyev/data-science/blob/main/np_malumotlar_turi3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [4]:
arr1 = np.array([1,2,3], dtype=np.float64) # bu float64 malumot turiga ega massiv
arr1

array([1., 2., 3.])

In [5]:
arr2 = np.array([1,2,3], dtype=np.float32) #bu float32 malumotlar turiga ega massiv
arr2

array([1., 2., 3.], dtype=float32)

In [6]:
arr1.dtype

dtype('float64')

In [8]:
arr = np.array([1,2,3,4])# int64
arr

array([1, 2, 3, 4])

In [9]:
arr.dtype

dtype('int64')

In [11]:
float_arr = arr.astype(np.float64)
float_arr.dtype

dtype('float64')

In [12]:
data = np.array([3.8,2.4,7.1,1.8]) #float64
data.dtype

dtype('float64')

In [13]:
data_int = data.astype(np.int64) #astype metodi int yoki float o'zgartirish uchun qo'llaniladi
data_int

array([3, 2, 7, 1])