<a href="https://colab.research.google.com/github/otabekqoroboyev/data-science/blob/main/numpy_array3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
data1 = [3.5, 4, 5, 8] #list ko'rinishida
arr1 = np.array(data1)

In [5]:
data1

[3.5, 4, 5, 8]

In [6]:
arr1

array([3.5, 4. , 5. , 8. ])

In [7]:
data2 = (2, 4, 8, 2.5, 9)
arr2 = np.array(data2)

In [8]:
data2

(2, 4, 8, 2.5, 9)

In [9]:
arr2

array([2. , 4. , 8. , 2.5, 9. ])

In [10]:
arr1.ndim

1

In [12]:
arr2.ndim

1

In [14]:
data3 = [[1,2,3,4],[5,6,7,8]] # list ichida list nested list deyiladi
arr3 = np.array(data3)

In [15]:
arr3

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [16]:
arr3.ndim

2

In [18]:
# shape va size funksiyalari
arr3.shape # qator va ustunlar sanaydi


(2, 4)

In [19]:
arr3.size # jadvaldagi elementlar soni

8

In [31]:
# zeros va ones funksiyalari
arr4 = np.zeros(shape =(2,4)) # faqat 0 ko'rinishida bo'ladi
arr4

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [32]:
arr5 = np.ones((2,4))
arr5

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [35]:
#arange funksiyasi 
arr6 = np.arange(2,20, 2)
arr6

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [36]:
arr7 =np.arange(20)
arr7

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])