<a href="https://colab.research.google.com/github/otabekqoroboyev/data-science/blob/main/tartiblash_np.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tartiblash
Sorting Numpy kutubxonasi orqali

In [14]:
import numpy as np

In [21]:
arr = np.random.randn(4) # 4ta taxminiy qimatdan tashkil topgan 
arr

array([-0.55608802,  0.3064454 ,  0.56031967, -0.3201278 ])

### `sort` funkiyasi

In [22]:
sorted_arr = np.sort(arr) # arr tartiblangan versiyasi 
sorted_arr

array([-0.55608802, -0.3201278 ,  0.3064454 ,  0.56031967])

In [25]:
arr.sort() #bu arr tartiblangan versiyasi to'g'ridan to'g'ri jaylashishi
arr

array([-0.55608802, -0.3201278 ,  0.3064454 ,  0.56031967])

In [27]:
#teskari tartiblash 
rev_arr = -np.sort(arr) #kattadan kichikka qarab tartiblaydi
rev_arr

array([ 0.55608802,  0.3201278 , -0.3064454 , -0.56031967])

In [29]:
arr2d = np.random.randn(2,4) #2 ga 4 rendom massiv
arr2d 


array([[-1.75020907, -0.36946766,  1.71924914, -0.88360705],
       [-0.68918879,  0.20474571,  0.02160193,  2.16285361]])

In [31]:
# axis = 0  ->> bu qator 
row_sort = np.sort(arr2d, axis=0)
row_sort

array([[-1.75020907, -0.36946766,  0.02160193, -0.88360705],
       [-0.68918879,  0.20474571,  1.71924914,  2.16285361]])

In [35]:
# axis = 1 -- >> bu ustun
row_srt = np.sort(arr2d, axis=1) # arr bo'yicha har bir ustunni tartiblaydi
row_srt

array([[-1.75020907, -0.88360705, -0.36946766,  1.71924914],
       [-0.68918879,  0.02160193,  0.20474571,  2.16285361]])