<a href="https://colab.research.google.com/github/otabekqoroboyev/data-science/blob/main/unversal_funksiyalar_np.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

### `sqrt`, `square`, `exp`, `log`, `modf`, `sign`, `isnan` funksiyalarini ko'rib chiqamiz

In [5]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.sqrt(arr) # batcha elementlarni yani 1dan 9 gacha ilidizni topadi

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [7]:
np.square(arr) # barcha elementlarni kvadratga oshiradi

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [8]:
np.exp(arr) #arr barcha elemwntlarinni eksponetini qaytaradi 

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [9]:
np.log(arr[1:]) # arr nomili massivli barcha elelmentlarni logarifimni hisoblaydi log e

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [10]:
arr1 = np.random.randn(6) #oltita iboratdan taxminiy massiv
arr1

array([-0.4681178 ,  0.97632467, -0.14742106,  0.09840768, -1.54583936,
       -1.46554254])

In [11]:
qoldiq, butun = np.modf(arr1) #bu qoldiq va butun qismi 2 ta massivga ajratadi

In [14]:
print(qoldiq)
print(butun)

[-0.4681178   0.97632467 -0.14742106  0.09840768 -0.54583936 -0.46554254]
[-0.  0. -0.  0. -1. -1.]


### `sign` funkisyasi massiv elementlarini qiymati manfiy bo'lsa `-1` va aksincha musbat bo'lsa `1` ni qaytaradi

In [15]:
np.sign(arr1) # bu massiv elementlarni -1 va 1 qilib qaytaradi

array([-1.,  1., -1.,  1., -1., -1.])

### `isnan` massivning elementlarida NaN ma'lumoti bo'lsa `True` qaytaradi va aksincha esa `False` qaytaradi

In [16]:
np.isnan(arr1)

array([False, False, False, False, False, False])

In [17]:
arr1[0] = np.nan # 0 elementmizni nan almashtirib qoydik

In [18]:
np.isnan(arr1)

array([ True, False, False, False, False, False])

Binary funksiyalari

In [19]:
# ikkita massiv yaratib olamiz
arr2 = np.random.randn(6)
arr3 = np.random.randn(6)
print(arr2)
print(arr3)

[-1.03647795  1.01091926 -1.54088147 -1.66726626 -0.24430658 -0.9100146 ]
[-1.14333716 -1.03248472 -1.09139209  0.54191091 -0.29040121  0.83039807]


In [20]:
np.add(arr2,arr3) # bu element arr2 va arr3 elementlarni mos ravishda qo'shib berarkan

array([-2.17981511, -0.02156546, -2.63227357, -1.12535535, -0.53470779,
       -0.07961652])

multiply - funksiyasi kopaytirib beradi

In [21]:
np.multiply(arr2,arr3)

array([ 1.18504376, -1.0437587 ,  1.68170586, -0.90350978,  0.07094693,
       -0.75567437])

maximum - funksiyasi

In [22]:
np.maximum(arr2,arr3) # arr2 va arr3 elementlarni o'zaro taqqoslab ozaro kattasini chiqaradi

array([-1.03647795,  1.01091926, -1.09139209,  0.54191091, -0.24430658,
        0.83039807])